### ISSUE TITLE
超好用！爱来自瓷器。

### ISSUE THREAD

**Issue by iyzyi** [Little-King2022/jstc_pic_uploader#1]
🥰🥰🥰

**Comment by iyzyi** [comment]
一开始想用安卓，配置起来太麻烦了，最后发现必须root才能搞定系统证书。
然后换ipad，没想到这个小程序没做适配，拍照键藏到了相机UI底下，没法点击。
最后两台windows，一个开小程序，一个开charles，搞定~（我以前是真不知道小程序可以在PC上用）
感谢作者🥰

**Comment by Little-King2022** [comment]
ipad开启台前调度，把微信窗口缩窄一点就有拍照按钮了哦
